import * as stylex from '@stylexjs/stylex'

export const color = stylex.defineConsts({
  brand50: 'var(--thc-brand-50)',
  brand600: 'var(--thc-brand-600)',
  brand700: 'var(--thc-brand-700)',
  brand800: 'var(--thc-brand-800)',
  brand900: 'var(--thc-brand-900)',
  gray50: 'var(--thc-gray-50)',
  gray100: 'var(--thc-gray-100)',
  gray200: 'var(--thc-gray-200)',
  gray300: 'var(--thc-gray-300)',
  gray400: 'var(--thc-gray-400)',
  gray500: 'var(--thc-gray-500)',
  gray600: 'var(--thc-gray-600)',
  gray700: 'var(--thc-gray-700)',
  gray800: 'var(--thc-gray-800)',
  gray900: 'var(--thc-gray-900)',
  gray950: 'var(--thc-gray-950)',
  primary: 'var(--thc-primary)',
  primaryActive: 'var(--thc-primary-active)',
  primaryTint: 'var(--thc-primary-tint)',
  primaryDeep: 'var(--thc-primary-deep)',
  onPrimary: 'var(--thc-on-primary)',
  canvas: 'var(--thc-canvas)',
  surfaceCard: 'var(--thc-surface-card)',
  surfaceSoft: 'var(--thc-surface-soft)',
  surfaceHover: 'var(--thc-surface-hover)',
  surfaceNav: 'var(--thc-surface-nav)',
  ink: 'var(--thc-ink)',
  bodyStrong: 'var(--thc-body-strong)',
  body: 'var(--thc-body)',
  meta: 'var(--thc-meta)',
  captionInk: 'var(--thc-caption-ink)',
  hairline: 'var(--thc-hairline)',
  hairlineStrong: 'var(--thc-hairline-strong)',
  inputBorder: 'var(--thc-input-border)',
  positive: 'var(--thc-positive)',
  negative: 'var(--thc-negative)',
  warning: 'var(--thc-warning)',
  neutralFlat: 'var(--thc-neutral-flat)',
})

export const overlay = stylex.defineConsts({
  scrim: 'var(--thc-overlay-scrim)',
  ink: 'var(--thc-overlay-ink)',
  muted: 'var(--thc-overlay-muted)',
  hover: 'var(--thc-overlay-hover)',
  track: 'var(--thc-overlay-track)',
})

export const motion = stylex.defineConsts({
  ease: 'var(--thc-ease)',
  easeSpring: 'var(--thc-ease-spring)',
  easeSmooth: 'var(--thc-ease-smooth)',
  durationFast: 'var(--thc-duration-fast)',
  durationMedium: 'var(--thc-duration-medium)',
  durationSlow: 'var(--thc-duration-slow)',
})

export const dia = stylex.defineConsts({
  c1: 'var(--thc-dia-1)',
  c2: 'var(--thc-dia-2)',
  c3: 'var(--thc-dia-3)',
  c4: 'var(--thc-dia-4)',
  c5: 'var(--thc-dia-5)',
})

export const text = stylex.defineConsts({
  fontDisplay: 'var(--thc-font-display)',
  fontSans: 'var(--thc-font-sans)',
  fontMono: 'var(--thc-font-mono)',
  sizeDisplay2xl: 'var(--thc-size-display-2xl)',
  sizeDisplayXl: 'var(--thc-size-display-xl)',
  sizeDisplayLg: 'var(--thc-size-display-lg)',
  sizeDisplayMd: 'var(--thc-size-display-md)',
  sizeDisplaySm: 'var(--thc-size-display-sm)',
  sizeDisplayXs: 'var(--thc-size-display-xs)',
  sizeBodyXl: 'var(--thc-size-body-xl)',
  sizeBodyLg: 'var(--thc-size-body-lg)',
  sizeBodyMd: 'var(--thc-size-body-md)',
  sizeBodySm: 'var(--thc-size-body-sm)',
  sizeCaption: 'var(--thc-size-caption)',
  sizeMicro: 'var(--thc-size-micro)',
  sizeCode: 'var(--thc-size-code)',
  leadingDisplay2xl: 'var(--thc-leading-display-2xl)',
  leadingDisplayXl: 'var(--thc-leading-display-xl)',
  leadingDisplayLg: 'var(--thc-leading-display-lg)',
  leadingDisplayMd: 'var(--thc-leading-display-md)',
  leadingDisplaySm: 'var(--thc-leading-display-sm)',
  leadingDisplayXs: 'var(--thc-leading-display-xs)',
  leadingBodyXl: 'var(--thc-leading-body-xl)',
  leadingBodyLg: 'var(--thc-leading-body-lg)',
  leadingBodyMd: 'var(--thc-leading-body-md)',
  leadingBodySm: 'var(--thc-leading-body-sm)',
  leadingCaption: 'var(--thc-leading-caption)',
  leadingMicro: 'var(--thc-leading-micro)',
  leadingCode: 'var(--thc-leading-code)',
  trackingDisplay2xl: 'var(--thc-tracking-display-2xl)',
  trackingDisplayXl: 'var(--thc-tracking-display-xl)',
  trackingDisplayLg: 'var(--thc-tracking-display-lg)',
  trackingDisplayMd: 'var(--thc-tracking-display-md)',
  trackingDisplaySm: 'var(--thc-tracking-display-sm)',
  trackingDisplayXs: 'var(--thc-tracking-display-xs)',
  trackingBody: 'var(--thc-tracking-body)',
  trackingBodySm: 'var(--thc-tracking-body-sm)',
  trackingLabel: 'var(--thc-tracking-label)',
  trackingEyebrow: 'var(--thc-tracking-eyebrow)',
  trackingAllcaps: 'var(--thc-tracking-allcaps)',
  weightRegular: 'var(--thc-weight-regular)',
  weightMedium: 'var(--thc-weight-medium)',
  weightSemibold: 'var(--thc-weight-semibold)',
})

export const space = stylex.defineConsts({
  xxs: 'var(--thc-space-xxs)',
  xs: 'var(--thc-space-xs)',
  sm: 'var(--thc-space-sm)',
  md: 'var(--thc-space-md)',
  lg: 'var(--thc-space-lg)',
  xl: 'var(--thc-space-xl)',
  x2xl: 'var(--thc-space-2xl)',
  x3xl: 'var(--thc-space-3xl)',
  x4xl: 'var(--thc-space-4xl)',
  x5xl: 'var(--thc-space-5xl)',
  x6xl: 'var(--thc-space-6xl)',
  section: 'var(--thc-space-section)',
})

export const radius = stylex.defineConsts({
  none: 'var(--thc-radius-none)',
  xs: 'var(--thc-radius-xs)',
  sm: 'var(--thc-radius-sm)',
  md: 'var(--thc-radius-md)',
  lg: 'var(--thc-radius-lg)',
  xl: 'var(--thc-radius-xl)',
  pillSm: 'var(--thc-radius-pill-sm)',
  pill: 'var(--thc-radius-pill)',
  full: 'var(--thc-radius-full)',
  card: 'var(--thc-radius-card)',
  input: 'var(--thc-radius-input)',
  action: 'var(--thc-radius-action)',
  pulse: 'var(--thc-radius-pulse)',
})

export const shadow = stylex.defineConsts({
  s0: 'var(--thc-shadow-0)',
  s1: 'var(--thc-shadow-1)',
  s2: 'var(--thc-shadow-2)',
  s3: 'var(--thc-shadow-3)',
  s4: 'var(--thc-shadow-4)',
  s5: 'var(--thc-shadow-5)',
  float: 'var(--thc-shadow-float)',
  modal: 'var(--thc-shadow-modal)',
})

export const layout = stylex.defineConsts({
  containerMax: 'var(--thc-container-max)',
  containerWide: 'var(--thc-container-wide)',
  proseMax: 'var(--thc-prose-max)',
  measureProse: 'var(--thc-measure-prose)',
  sidePanelMax: 'var(--thc-side-panel-max)',
  focusRing: 'var(--thc-focus-ring)',
})
